cache: cargo
dist: trusty
language: generic
language: rust
rust: stable
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=xargo
    - DEPLOY_VERSION=stable
    - TARGET=x86_64-unknown-linux-gnu

matrix:
  include:
    # OSX
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

    - env: TARGET=i686-apple-darwin
      os: osx
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

    # Linux
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    # This target is handled by the default build job
    # - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl

    - env: TARGET=i686-unknown-linux-gnu
      rust: nightly
    - env: TARGET=i686-unknown-linux-musl
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-musl
      rust: nightly

install:
  # curl: cargo + rustc
  # case: rust-std
  # rustup: rust-src
  - if [ -z $TRAVIS_TAG ] || [ $TRAVIS_RUST_VERSION = $DEPLOY_VERSION ]; then
      curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y;
      source ~/.cargo/env;
      case $TARGET in
        x86_64-apple-darwin | x86_64-unknown-linux-gnu) ;;
        *) rustup target add $TARGET ;;
      esac;
      rustup component add rust-src;
    fi

script:
  # chmod: Travis can't cache files that are not readable by "others"
  - if [ -z $TRAVIS_TAG ] || [ $TRAVIS_RUST_VERSION = $DEPLOY_VERSION ]; then
      cargo generate-lockfile;
      if [[ $TRAVIS_OS_NAME = linux ]]; then
        sh ci/run-docker.sh $TARGET;
      else
        sh ci/run.sh;
      fi;
      chmod -R a+r $HOME/.cargo;
    fi

before_deploy:
  - sh ci/package.sh $TARGET

deploy:
  provider: releases
  api_key:
    secure: RzmRdZJAyz9Bp1NLQs26ey2YRMi21qn0Hid1kqW+GR+M9rHM4QEJlhfHlmh/MzRoR2aU/DcWIsB+IgZvpwxzAscy1CapnlVexXTXnp6ezLHYzJ6H+3IOE8rQ6wanXtPAaMdhnbnyPDgR12wgWksxcMxaChwiInYQmtSbihVd8PgJU8hqREPtDzaLtjo3rLp+4uuxVRVE7Fkv9Wve5X7yig2t7s+18l5yhOfSUS+aPgUyJlPo1hHyIMvIE9OF1KdkYNu5iN4wFrjHTIvROqbW5vAgiHRjJLb4H782b01SfVuCVH/ea1vmyfmX+vQ7g2VKQlzZnhJl0AcsdR60D+QzfHCZ/9KG2P9ciUtr8PUyqWVXtwctVhR6PYgkwl9p92ubqylj9E1vkLMFKC1o5M9Jihyc/16FAIbhnmossOMCKIMkhOJRHBlJO0wfyLTmKbyzSNiEWvHbX7MqQC0FYe7IfMgbQSq0MYq63GaOEd/Ne1r3FX6+jqrMO3Pohq08YOlbE1J5x3Zs5xZ9WdyDCKuR/kb/+qnJkqZjcaTRLTO8b/4lSYCbWydme6ynpoxd/Mz9gplhJxPInUpx87sUrcEg0xKSjPDu95B4KRkb8EhD+ybT+7QLAyfSzQtnf4+u49I7zwI/8sCiAvepMVIXIr4rQZ5f1PJJZcGbVwT3zi49xsA=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  # don't delete the target directory
  skip_cleanup: true
  on:
    condition: $TRAVIS_RUST_VERSION = $DEPLOY_VERSION
    tags: true

cache:
  directories:
    - $HOME/.cargo
    - target

branches:
  only:
    # Release tags
    - /^v\d+\.\d+\.\d+.*$/
    - auto
    - try

notifications:
  email:
    on_success: never
  webhooks: https://homu.herokuapp.com/travis
