environment:
  global:
    CRATE_NAME: xargo
    RUST_VERSION: stable
  matrix:
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc

    - TARGET: i686-pc-windows-msvc
      RUST_VERSION: nightly
    - TARGET: x86_64-pc-windows-msvc
      RUST_VERSION: nightly

install:
  - ps: ci\install.ps1

build: false

test_script:
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      if [%RUST_VERSION%]==[nightly] (
        cargo test --target %TARGET%
      ) else (
        cargo build --target %TARGET%
      )
    ) else (
      cargo rustc --target %TARGET% --release -- -C lto
    )

before_deploy:
  - ps: ci\package.ps1

deploy:
  description: 'Windows release'
  artifact: /.*\.zip/
  auth_token:
    secure: bQ29dEXeNG5VP2hQcWiZ1xsfmkGosteCDNeYu/cXTX4lOeghOp0qANpQXmGfal29
  provider: GitHub
  on:
    RUST_VERSION: stable
    appveyor_repo_tag: true

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    # Release tags
    - /^v\d+\.\d+\.\d+.*$/
    - auto
    - try

notifications:
  - provider: Email
    on_build_success: false
